apiVersion: v1
kind: Service
metadata:
  name: cloudlens-backend
  namespace: cloudlens
  labels:
    app.kubernetes.io/name: cloudlens
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudlens
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: http

