apiVersion: v1
kind: Secret
metadata:
  name: cloudlens-cloud-credentials
  namespace: cloudlens
type: Opaque
stringData:
  ALIYUN_ACCESS_KEY_ID: ""
  ALIYUN_ACCESS_KEY_SECRET: ""
  ALIYUN_REGION: "cn-hangzhou"
  ALIYUN_REGIONS: "cn-hangzhou"
  HUAWEI_ACCESS_KEY_ID: ""
  HUAWEI_ACCESS_KEY_SECRET: ""
  HUAWEI_PROJECT_ID: ""
  HUAWEI_REGION: "cn-south-1"
  HUAWEI_REGIONS: "cn-south-1"
  AI_API_KEY: ""

