apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudlens-backend
  namespace: cloudlens
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudlens-frontend
  namespace: cloudlens
automountServiceAccountToken: false

